version = "1.1.15"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = ""
client_active = "{icon} "
client = "{icon} "
workspace = "{id}: {clients}"
workspace_empty = "{id}: "
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon} ]{delim}"

[class_active]
DEFAULT=""

[title_in_class."(firefox|librewolf|chrom.*)"]
"(?i)youtube" = "󰗃"

[title_in_class."(?i)kitty"]
Yazi = "󰇥"

[class]
DEFAULT = ""

"(?i)kitty" = ""

"obsidian" = ""
"haguichi" = ""
"firefox"  = "󰈹"
"discord"  = ""
"evince"   = ""
"totem"    = "󱉺"

"org.gnome.Calculator" = ""
"org.gnome.Software"   = "󱗼"
"org.gnome.Nautilus"   = "󰪶"
"org.gnome.Loupe"      = ""

"com.moonlight_stream.Moonlight"= "󰢹"
"ONLYOFFICE Desktop Editors"    = ""
"Mendeley Reference Manager"    = ""
"com.saivert.pwvucontrol"= "󰴸"
"com.usebottles.bottles" = ""
"org.telegram.desktop"   = ""
"libreoffice-writer"     = ""
"transmission.gtk" = ""
"teams-for-linux"  = "󰊻"
"dosbox-staging"   = "󰚴"
"localsend_app"    = "󱗿"
"virt-manager"     = ""
"org.openscad."    = ""

[exclude]
"" = "^$"
